# Generated by Django 4.1.3 on 2022-11-29 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('name', models.TextField(max_length=64)),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('text', models.TextField(max_length=1024)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='commands.command')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-create_date'],
            },
        ),
    ]
