# Generated by Django 4.1.3 on 2022-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
