# Generated by Django 4.1.3 on 2022-12-04 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_command_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('max_amount_of_bots', models.SmallIntegerField()),
                ('number_of_messages_min', models.SmallIntegerField()),
                ('number_of_messages_max', models.SmallIntegerField()),
                ('delay_between_messages_min', models.SmallIntegerField()),
                ('delay_between_messages_max', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('room_id', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
