# Generated by Django 4.1.3 on 2022-12-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_apikey_bot_generalsettings_roomid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
