# Generated by Django 4.1.3 on 2022-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_alter_generalsettings_options_alter_bot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='geo',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
    ]
