# Generated by Django 4.1.3 on 2022-12-09 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0007_generalsettings_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='time',
            field=models.TimeField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('write_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelines', to='commands.command')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_settings', to='commands.timeline'),
        ),
    ]
