# Generated by Django 4.1.3 on 2022-12-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0008_command_time_timeline_generalsettings_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='commands.timeline'),
        ),
    ]
