# Generated by Django 4.1.3 on 2022-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0009_remove_timeline_command_command_timeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-create_date'], 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
