# Generated by Django 4.1.3 on 2023-01-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0010_alter_timeline_options_alter_timeline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomid',
            name='room_name',
            field=models.CharField(default='new_test_room', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomid',
            name='room_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
